# This file is a configuration file for loops rails plugin
#

# This section is used to control loops manager
global:
  logger: log/loops/global.log
  poll_period: 5
  workers_engine: fork

# Each record in this section represents one loop which could be ran using loops plugin.
# Each loop should have a file in app/loops directory with the same name as its config record.
loops:

  generic_monitor:
    loop_name: monitor/website
    type: simple
    workers_number: 1
    logger: log/loops/generic.log
    
    # disabled: true
